//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usuarios.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosExternos
    {
        public string usr_cuenta { get; set; }
        public string usr_password { get; set; }
        public string usr_nombre { get; set; }
        public string usr_apellido { get; set; }
        public string usr_email { get; set; }
        public bool usr_activo { get; set; }
        public string usr_telefono { get; set; }
        public string usr_direccion { get; set; }
        public decimal usr_rut { get; set; }
        public string usr_dv { get; set; }
        public System.DateTime usr_fecha_act { get; set; }
        public string usr_empresa { get; set; }
        public string emp_ciudad { get; set; }
        public string emp_telefono { get; set; }
        public string emp_region { get; set; }
        public decimal emp_roluni { get; set; }
        public string emp_dv { get; set; }
        public UsuariosExternos()
        {
        }

    }

}
